groups=['Paul Bril',
'Otto van Veen ',
'Agostino Carracci',
'Hendrik Goltzius',
'Annibale Carracci',
'Hendrick Cornelisz Vroom',
'Adam van Noort',
'Francisco Pacheco',
'Francisco Ribalta',
'Jan Brueghel',
'Caravage',
'Giulio Cesare Procaccini',
'Goerges Lallemant',
'Guido Reni',
'Francisco de Herrera le Vie',
'Pierre Paul Rubens',
'Agostino Tassi',
'Adam Elsheimer',
'Pieter Jansz Saenredam',
'Frans Snyders',
'Frans Hals',
'Willem van Swanenburg',
'Bernando Strozzi',
'Cornelis de Vos',
'Hendrick Avercamp',
'Esaias van de Velde',
'Hendrick ter Brugghen',
'Domenico Fiasella',
'Nicolas Tournier',
'Simon Vouet',
'José de Ribera',
'Le Guerchin', 
'Gerrit van Honthorst',
'Goerges de la Tour',
'Jacob Jordaens',
'Artemisia Gentileschi',
'Clara Peeters',
'Nicolas Poussin',
'Dirck van Baburen',
'Jacques Stella',
'Jan van Goyen',
'Juan van der Hamen',
'Johannes Blaeu',
'Pierre de Cortone',
'Pieter Claesz',
'Francisco de Zurbaran',
'Gian Lorenzo Bernini',
'Antoine van Dyck', 
'Diego Vélasquez ',
'Pieter Codde',
'Claude Gellée',
'Matthias Stom',
'Thomas Smith', 
'Simon de Vlieger',
'Salomon van Ryusdael',
'Theodoor van Thulden',
'Rembrandt',
'Gérard Dou',
'Salvator Rosa',
'Ferdinand Bol',
'Gerard ter Borch', 
'Bartolomé Esteban Murillo',
'Charles le Brun',
'Jan Steen', 
'Pieter de Hooch',
'Adam François van der Meulen',
'Johannes Vermeer',
'Nicolas Maes',
'Jacob Ochtervelt',
'Luca Giordano',
'Baciccio',
'Abraham Storck',
'Michiel van Musscher',
'John Riley',
'Jan Luyken',
'Giuseppe Maria Crespi',
'Jean-Baptiste van Mour', 
'Sebastiano Conca',
'Canaletto',
'Jean Siméon Chardin',
'Johann Georg Pinsel',
'Francesco Guardi',
'Giovanni Battista Piranesi',
'Raphaël Mengs' ]