groups=['Tosa Mitsuoki',
'Hakuin Ekaku',
'Yosa Buson', 
'Ito Jakuchu', 
'Enji Torei', 
'Ike no Taiga', 
'Kogan Gengei', 
'Sengau', 
'Utamoro', 
'Hokusai', 
'Utagawa Toyokuni', 
'Utagawa Toyokuni II',
'Toyota Hokkei', 
'Utagawa Kunisada', 
'Keisai Eisen', 
'Sharaku', 
'Hiroshige', 
'Utagawa Kuniyoshi', 
'Shibata Zeshin', 
'Utagawa Kunisada II',
'Utagawa Sadatora', 
'Tomioka Tessai', 
'Yoshitoshi']